/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FloatingNav: typeof import('./../../src/components/FloatingNav/index.vue')['default']
    Footer: typeof import('./../../src/components/SearchMenu/Footer.vue')['default']
    InkEffect: typeof import('./../../src/components/InkEffect/index.vue')['default']
    List: typeof import('./../../src/components/Notify/List.vue')['default']
    Modal: typeof import('./../../src/components/SearchMenu/Modal.vue')['default']
    Notify: typeof import('./../../src/components/Notify/index.vue')['default']
    Result: typeof import('./../../src/components/SearchMenu/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SakuraEffect: typeof import('./../../src/components/SakuraEffect/index.vue')['default']
    Screenfull: typeof import('./../../src/components/Screenfull/index.vue')['default']
    SearchMenu: typeof import('./../../src/components/SearchMenu/index.vue')['default']
    TechEffect: typeof import('./../../src/components/TechEffect/index.vue')['default']
    ThemeSwitch: typeof import('./../../src/components/ThemeSwitch/index.vue')['default']
    TopNavBar: typeof import('./../../src/components/TopNavBar/index.vue')['default']
  }
}
